# Railway Configuration for Experts Panel

[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
# Disable Railway health check and use Docker internal health check
# healthcheckPath = "/health"
# healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Use Docker internal health check instead of Railway external check

# Environment variables will be set in Railway dashboard
# These are just documentation for required variables

[variables]
# OpenAI API (required)
OPENAI_API_KEY = ""

# Database (Railway provides PostgreSQL)
DATABASE_URL = ""

# Production settings
PRODUCTION_ORIGIN = ""
API_HOST = "0.0.0.0"
API_PORT = "8000"
LOG_LEVEL = "INFO"

# Railway specific
PORT = "8000"
RAILWAY_ENVIRONMENT = "production"

# Optional: Telegram API for sync
TELEGRAM_API_ID = ""
TELEGRAM_API_HASH = ""
TELEGRAM_CHANNEL = ""

# Railway will automatically build from the root directory
# using the Dockerfile in the backend directory

# Railway will automatically use port 8000 from the Dockerfile
# and configure health checks based on the HEALTHCHECK instruction