"""Search probes: historical retrieval diagnostics and source-reviewed agent cases.

Ground truth provenance:
- questions: output/scout_runs/*/question.txt (real runs, not synthetic);
- legacy expected_keys came from run citations: existence alone is NOT semantic gold;
- reviewed_at + rubric + evidence mark cases manually checked against full Scout show;
- new historical_repair questions guard repaired source details;
- gap/negative_control fixtures pin honest-abstain behavior.
Never rebuild gold from the answers being scored. Review sources first; keep
legacy diagnostics separate from source-reviewed answer acceptance.
"""

from __future__ import annotations

FIXTURES: list[dict] = [
    {
        'id': 'coverage_previz_blocking',
        'kind': 'hit',
        'tags': ['broad', 'scope_all', 'freshness_tool'],
        'question': 'Проверь покрытие корпуса (эксперты Панели + video_hub) по 5 темам. Для каждой: покрыто (дай source_key и краткую цитату) или gap. Темы: 1) превиз/блокинг сцены в Blender перед AI-генерацией видео для экономии кредитов; 2) генерация посекундного промта по видео-референсу блокинга; 3) консистентность персонажей и правило 180 градусов в мульти-персонажных сценах; 4) сложные движения камеры (орбита, пролёт сквозь этажи, robotic arm) через 3D-блокинг; 5) экономика кредитов AI-видеогенерации (стоимость дублей, оптимизация расхода).',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['video_hub:737101800', 'video_hub:168482184', 'video_hub:726332883', 'cgevent:16660'],
        'min_hits': 2,
        'note': 'фасет покрытия: превиз/блокинг в Blender',
        'provenance': 'scout_run:20260920-100332-460653',
    },
    {
        'id': 'coverage_persecond_prompt',
        'kind': 'hit',
        'tags': ['broad', 'scope_all', 'freshness_tool'],
        'question': 'Проверь покрытие корпуса (эксперты Панели + video_hub) по 5 темам. Для каждой: покрыто (дай source_key и краткую цитату) или gap. Темы: 1) превиз/блокинг сцены в Blender перед AI-генерацией видео для экономии кредитов; 2) генерация посекундного промта по видео-референсу блокинга; 3) консистентность персонажей и правило 180 градусов в мульти-персонажных сценах; 4) сложные движения камеры (орбита, пролёт сквозь этажи, robotic arm) через 3D-блокинг; 5) экономика кредитов AI-видеогенерации (стоимость дублей, оптимизация расхода).',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['video_hub:23777140', 'video_hub:998318835', 'video_hub:705705922', 'cgevent:16312'],
        'min_hits': 2,
        'note': 'фасет покрытия: посекундный промт по блокингу',
        'provenance': 'scout_run:20260920-100332-460653',
    },
    {
        'id': 'coverage_pravilo180',
        'kind': 'hit',
        'tags': ['broad', 'scope_all', 'freshness_craft'],
        'question': 'Проверь покрытие корпуса (эксперты Панели + video_hub) по 5 темам. Для каждой: покрыто (дай source_key и краткую цитату) или gap. Темы: 1) превиз/блокинг сцены в Blender перед AI-генерацией видео для экономии кредитов; 2) генерация посекундного промта по видео-референсу блокинга; 3) консистентность персонажей и правило 180 градусов в мульти-персонажных сценах; 4) сложные движения камеры (орбита, пролёт сквозь этажи, robotic arm) через 3D-блокинг; 5) экономика кредитов AI-видеогенерации (стоимость дублей, оптимизация расхода).',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['neyrograph:4425', 'acidcrunch:2177'],
        'min_hits': 2,
        'note': 'фасет покрытия: правило 180 градусов',
        'provenance': 'scout_run:20260920-100332-460653',
    },
    {
        'id': 'coverage_camera_moves',
        'kind': 'hit',
        'tags': ['broad', 'scope_all'],
        'question': 'Проверь покрытие корпуса (эксперты Панели + video_hub) по 5 темам. Для каждой: покрыто (дай source_key и краткую цитату) или gap. Темы: 1) превиз/блокинг сцены в Blender перед AI-генерацией видео для экономии кредитов; 2) генерация посекундного промта по видео-референсу блокинга; 3) консистентность персонажей и правило 180 градусов в мульти-персонажных сценах; 4) сложные движения камеры (орбита, пролёт сквозь этажи, robotic arm) через 3D-блокинг; 5) экономика кредитов AI-видеогенерации (стоимость дублей, оптимизация расхода).',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['neyrograph:4714', 'video_hub:34425000', 'video_hub:908346948'],
        'min_hits': 2,
        'note': 'фасет покрытия: сложные движения камеры',
        'provenance': 'scout_run:20260920-100332-460653',
    },
    {
        'id': 'coverage_credits',
        'kind': 'hit',
        'tags': ['broad', 'scope_all'],
        'question': 'Проверь покрытие корпуса (эксперты Панели + video_hub) по 5 темам. Для каждой: покрыто (дай source_key и краткую цитату) или gap. Темы: 1) превиз/блокинг сцены в Blender перед AI-генерацией видео для экономии кредитов; 2) генерация посекундного промта по видео-референсу блокинга; 3) консистентность персонажей и правило 180 градусов в мульти-персонажных сценах; 4) сложные движения камеры (орбита, пролёт сквозь этажи, robotic arm) через 3D-блокинг; 5) экономика кредитов AI-видеогенерации (стоимость дублей, оптимизация расхода).',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['cgevent:16497', 'video_hub:368890709', 'video_hub:737101800'],
        'min_hits': 2,
        'note': 'фасет покрытия: экономия кредитов',
        'provenance': 'scout_run:20260920-100332-460653',
    },
    {
        'id': 'aleph_camera_acidcrunch',
        'kind': 'hit',
        'tags': ['scope_expert', 'freshness_craft'],
        'question': 'Посмотри, что у acidcrunch написано про камеру в модели Aleph (Runway Aleph). Если сигнала нет — скажи честно.',
        'query_variants': [],
        'search_args': ['--experts', 'acidcrunch'],
        'expected_keys': ['acidcrunch:1350', 'acidcrunch:1276', 'acidcrunch:1320', 'acidcrunch:1335'],
        'min_hits': 1,
        'note': 'один эксперт, источники 2025 года',
        'provenance': 'scout_run:20260914-000628-1211929',
        'reviewed_at': '2026-09-30',
        'rubric': 'Ответ только по acidcrunch: конкретное управление камерой Aleph; не выдавать Gen-4 References за Aleph.',
        'evidence': {'acidcrunch:1350': 'В Aleph это тоже работает.', 'acidcrunch:1276': 'копировать траекторию камеры', 'acidcrunch:1320': 'Менять ракурс съёмки', 'acidcrunch:1335': 'Extreme zoom in x 100'},
    },
    {
        'id': 'kling_o3_cgevent',
        'kind': 'hit',
        'tags': ['scope_expert'],
        'question': 'По эксперту cgevent (Tsyptsyn, Метаверсище и ИИще): как правильно использовать Kling O3 для видеогенерации? Нужны конкретные приёмы и источники.',
        'query_variants': [],
        'search_args': ['--experts', 'cgevent'],
        'expected_keys': ['cgevent:15685', 'cgevent:15729', 'cgevent:15973', 'cgevent:16191', 'cgevent:16296', 'cgevent:16375'],
        'min_hits': 2,
        'note': 'скоуп: конкретный эксперт',
        'provenance': 'scout_run:20260915-111230-1491667',
    },
    {
        'id': 'kling25_visual',
        'kind': 'hit',
        'tags': ['scope_group', 'freshness_tool'],
        'question': 'По визуалам: что пишут про Kling 2.5? 1-2 источника.',
        'query_variants': [],
        'search_args': ['--group', 'visual'],
        'expected_keys': ['acidcrunch:1597', 'acidcrunch:1824', 'strangedalle:1326'],
        'min_hits': 2,
        'note': 'скоуп: группа visual',
        'provenance': 'scout_run:20260914-000302-1210917',
    },
    {
        'id': 'mastery_levels',
        'kind': 'hit',
        'tags': ['broad', 'freshness_craft'],
        'question': 'Есть ли в корпусе ступенчатые модели мастерства AI-видео (уровни контроля: text-to-video, image-to-video, секвенции, performance transfer, агенты) и экономика стоимости одного удачного шота — сколько генераций и кредитов уходит на один usable shot на каждом уровне контроля? Дай источники с source_key.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:2707', 'acidcrunch:2792', 'cgevent:16312', 'iideyalogiya:1775', 'neyrograph:4606', 'neyrograph:4702'],
        'min_hits': 2,
        'note': 'ступенчатые уровни мастерства',
        'provenance': 'scout_run:20260922-102409-1732310',
    },
    {
        'id': 'avatar_face_consistency',
        'kind': 'hit',
        'tags': ['scope_videohub', 'freshness_tool'],
        'question': "Что в корпусе экспертов про создание AI-аватара с консистентностью лица: character sheet (полный рост + крупный план), перенос персонажа в разные локации с сохранением лица, клонирование/замена голоса и lip sync 'говорит на камеру' против нарратива? Есть ли конкретные приёмы?",
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:2771', 'cgevent:16753', 'iideyalogiya:1914', 'neyrograph:4154', 'neyrograph:4422', 'neyrograph:4519'],
        'min_hits': 2,
        'note': 'аватары/character sheet, свежие сегменты',
        'provenance': 'scout_run:20260929-090052-4027384',
    },
    {
        'id': 'blender_short_film_pipeline',
        'kind': 'hit',
        'tags': ['scope_videohub', 'freshness_tool'],
        'question': "Что в корпусе про пайплайн анимации короткометражки Blender + AI-генерация: (1) previs в Blender как гайд для движений камеры, тайминга и squash&stretch в AI-видео, (2) художественное направление - стилизованные 3D-персонажи в акварельном мире, ручная доработка в Photoshop, (3) тесты дизайнов до продакшна и освещения, (4) 'почему ИИ слаб в тонкой актёрской игре персонажей', честные провалы генераций?",
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:2792', 'cgevent:16236', 'cgevent:16651', 'cgevent:16660', 'cgevent:16675', 'iideyalogiya:1970'],
        'min_hits': 2,
        'note': 'Blender previs -> AI, свежие сегменты',
        'provenance': 'scout_run:20260929-092157-4036307',
    },
    {
        'id': 'higgsfield_videohub_inventory',
        'kind': 'hit',
        'tags': ['scope_videohub', 'broad'],
        'question': 'Какой контент, связанный с Higgsfield (Higgsfield AI), уже есть в корпусе VideoHub? Перечисли, какие видео, модели (например Soul, DoP, Seedance, Cinema Studio, Kling, Veo и т.п.), техники и темы по Higgsfield уже покрыты в сегментах экспертов. Нужен максимально полный инвентарь: названия/темы видео-источников и о чём они.',
        'query_variants': [],
        'search_args': ['--experts', 'video_hub'],
        'expected_keys': ['video_hub:575947525', 'video_hub:679225094', 'video_hub:759787428'],
        'min_hits': 2,
        'note': 'Диагностика retrieval по выборке VideoHub; три ключа не доказывают полноту инвентаря. Telegram исключён из gold согласно вопросу.',
        'provenance': 'scout_run:20260921-115241-1220614',
    },
    {
        'id': 'grid_prompting',
        'kind': 'hit',
        'tags': ['broad'],
        'question': 'Grid prompting for AI video: creating a single image with a 3x3 grid of nine film stills (nine equal panels) and then animating between the panels sequentially in one long video generation to get a multi-shot sequence with consistency. Also: first-frame plus last-frame interpolation to control the start and end of a shot while the model decides the middle. Do practitioners use these techniques? Give sources with source_key.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:2044', 'iideyalogiya:1304', 'iideyalogiya:1388', 'strangedalle:1348', 'video_hub:531461744', 'video_hub:102636863', 'video_hub:619811946'],
        'min_hits': 2,
        'note': 'узкая техника: grid 3x3',
        'provenance': 'scout_run:20260922-101956-1725373',
        'required_groups': {'grid_animation': ['acidcrunch:2044', 'video_hub:102636863'], 'first_last_frame': ['strangedalle:1348', 'video_hub:619811946']},
        'reviewed_at': '2026-09-30',
        'rubric': 'Различить создание сетки, её анимацию и first/last interpolation. Статическая сетка сама по себе не подтверждает анимацию.',
        'evidence': {'acidcrunch:2044': 'Работают сетки сцены 3×3', 'iideyalogiya:1304': 'Generate a cohesive 3x3 grid', 'iideyalogiya:1388': 'a clean 3×3 storyboard grid', 'strangedalle:1348': 'start-end frame', 'video_hub:531461744': 'a 3x3 grid of nine film stills', 'video_hub:102636863': 'Animate each frame as an individual shot', 'video_hub:619811946': 'the video will interpolate between these two exact frames.'},
    },
    {
        'id': 'character_likeness_longform',
        'kind': 'hit',
        'tags': ['broad', 'freshness_craft'],
        'question': 'How do practitioners keep character likeness and visual world consistent across many shots of a longer AI-generated film? I am looking for: character reference sheets generated from real photos of a real person, a written rules document for the world (location, flat overcast lighting, color palette with exact hex codes, recurring prop motifs, locked-off camera at eye height), and reports of likeness drift across shots. Give 3-5 sources with source_key.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['cgevent:16480', 'iideyalogiya:1904', 'iideyalogiya:1947', 'strangedalle:1504', 'video_hub:481640535', 'video_hub:5056987'],
        'min_hits': 2,
        'note': 'консистентность в длинных формах',
        'provenance': 'scout_run:20260922-100552-1704215',
    },
    {
        'id': 'realism_in_ai_video',
        'kind': 'hit',
        'tags': ['broad', 'freshness_craft'],
        'question': "Realism in AI-generated video: what actually makes a shot look real (motion/physics, natural light behaviour, small human traces), and the practice of deliberately adding imperfection to generated footage to kill the AI look. What does the corpus have on AI video realism and on 'adding imperfection' (shaky camera, imperfect framing, natural micro-motions)? Give sources with source_key and honest gaps.",
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:2760', 'acidcrunch:2787', 'acidcrunch:2792', 'cgevent:16135', 'cgevent:16553', 'cgevent:16651'],
        'min_hits': 2,
        'note': 'реализм: motion/physics/свет',
        'provenance': 'scout_run:20260923-230246-2263553',
    },
    {
        'id': 'credits_economy',
        'kind': 'hit',
        'tags': ['broad'],
        'question': 'Что в корпусе про экономию кредитов в AI-видео-продакшене и мастеринг платформы Higgsfield: (1) дисциплина промта до генерации - проработка сцены до роллов, чтобы не жечь кредиты, (2) character sheet split-frame (полный рост + крупный план) с текстурой кожи, белый фон, (3) общий пайплайн платформы: image workspace -> scene build -> video generation, (4) чем Higgsfield отличается от голого Seedance в экономике?',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['cgevent:16322', 'acidcrunch:2611', 'acidcrunch:2644', 'acidcrunch:2771', 'acidcrunch:550', 'cgevent:16041'],
        'min_hits': 2,
        'note': 'экономия кредитов, мастеринг',
        'provenance': 'scout_run:20260929-091715-4034541',
    },
    {
        'id': 'speech_direction_audio_prompt',
        'kind': 'hit',
        'tags': ['broad'],
        'question': "English probe: what does the corpus say about these specific AI video techniques: (1) writing speech direction INTO the video audio prompt - 'spoken on camera with mouth moving' vs narration/voiceover, (2) counting script words for video duration - about 75 words per 30 seconds or the model fills silence, (3) generating multiple location transitions inside ONE video generation call with several reference images, (4) voice change / training a custom voice from a recording vs TTS presets? Concrete source_key citations please.",
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['cgevent:16753', 'iideyalogiya:1914', 'neyrograph:4573', 'video_hub:139865057', 'video_hub:231192822'],
        'min_hits': 2,
        'note': 'Исторический многосоставный вопрос. Удалён video_hub:293918715: преимущества grid prompting не подтверждают speech direction.',
        'provenance': 'scout_run:20260929-090304-4028516',
    },
    {
        'id': 'kling_elements_stability',
        'kind': 'hit',
        'tags': ['stability', 'freshness_tool'],
        'question': 'Что такое Kling Elements? Один источник, кратко.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['acidcrunch:371', 'doronin:394', 'strangedalle:1066', 'polyakov:128'],
        'min_hits': 1,
        'note': 'стабильность: вопрос гонялся 4 раза',
        'provenance': 'scout_run:20260913-233219-1202872',
        'max_sources': 1,
        'reviewed_at': '2026-09-30',
        'rubric': 'Один прочитанный источник из допустимых альтернатив достаточен; объяснить использование изображений элементов.',
        'evidence': {'acidcrunch:371': 'Просто загружаете до 4 изображений', 'doronin:394': 'Поместить один понятный Клингу элемент', 'strangedalle:1066': 'соединять различные картинки (до 4 штук)', 'polyakov:128': 'промпт + действующие лица.'},
    },
    {
        'id': 'ae_motion_graphics_agent',
        'kind': 'hit',
        'tags': ['broad', 'scope_videohub'],
        'question': 'English probe: corpus coverage of (1) After Effects plugin skills/instructions that let an AI agent build motion graphics compositions directly, (2) using video references to convey rhythm and typography in motion design prompts, (3) promo video brief structure - scenes, visual style, how elements should move, (4) AI-generated motion graphics with editable After Effects project files as deliverable? source_key citations.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['cgevent:16296', 'cgevent:16312', 'neyrograph:4623', 'video_hub:246201519', 'video_hub:306464563', 'video_hub:363651573'],
        'min_hits': 2,
        'note': 'EN: AE-плагин/агент для моушн-графики',
        'provenance': 'scout_run:20260929-091409-4033187',
    },
    {
        'id': 'minimax_degradation',
        'kind': 'gap',
        'tags': ['model_separation', 'partial_context'],
        'question': 'Найди практические свидетельства по MiniMax H3: резкая деградация reference-to-video после замены двух image references и небольшой правки prompt при прежнем clay-видео12.5с,6изображениях,13с output. Симптомы: перенос временных цветов clay в финал, пенные кольца несмотря на отрицания, лишние объекты, дрейф камеры. Особенно интересуют binding Video/Picture/Subject, Context-IR/rewrite, reAPI prompt expansion/seed, конфликт референсов и контролируемая диагностика. Отдели H3 от других моделей и hosted от local; нужны источники/даты и честные пробелы, не диагноз проекта.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': [],
        'min_hits': 0,
        'note': 'Прямой описанный кейс H3 не подтверждён. Старые ключи были общими новостями H3 и другими моделями Seedance/Cinema Studio, не доказательством диагностики.',
        'provenance': 'scout_run:20260923-232200-2292414',
        'reviewed_at': '2026-09-30',
        'rubric': 'Честно обозначить отсутствие точного кейса. Общие данные H3 допустимы только как контекст; Seedance не доказывает причины сбоя H3.',
        'allow_context_citations': True,
        'evidence': {},
    },
    {
        'id': 'hypermotion_gap',
        'kind': 'hit',
        'tags': ['historical_gap_closed', 'scope_all'],
        'question': 'Проверь покрытие корпуса (покрыто + source_key / gap): гипермоушн-реклама продуктов — разлетающаяся банка, осколки стекла/льда, замороженные фрукты как продуктовый макро-шот.',
        'query_variants': [],
        'search_args': [],
        'expected_keys': ['video_hub:468785115'],
        'min_hits': 1,
        'note': 'Бывший gap закрыт: прямой hypermotion-кейс банки, фруктов и льда. Не требовать отсутствующий разбор осколков стекла.',
        'provenance': 'scout_run:20260920-100750-467477',
        'reviewed_at': '2026-09-30',
        'rubric': 'Найти рекламу банки с фруктами/льдом и Blender blocking. Отдельные неподтверждённые детали не придумывать.',
        'evidence': {'video_hub:468785115': 'Can explodes into slices, fruit cracks open, ice floats, and everything freezes mid-air.'},
    },
    {
        'id': 'morph_pravilo180',
        'kind': 'hit',
        'tags': ['morphology', 'freshness_craft'],
        'question': 'правило 180 градусов в AI-видео',
        'query_variants': ['правило 180 градусов в AI-видео', 'правила ста восьмидесяти градусов', '180-градусный разворот сцены', 'правилом 180 градусов'],
        'search_args': [],
        'expected_keys': ['neyrograph:4425', 'acidcrunch:2177'],
        'min_hits': 2,
        'note': 'морфо-тест FTS: ключи подтверждены ответом прогона 20260920-100332',
        'provenance': '20260920-100332-460653',
    },
    {
        'id': 'morph_credits',
        'kind': 'hit',
        'tags': ['morphology'],
        'question': 'экономия кредитов AI-видеогенерации',
        'query_variants': ['экономия кредитов AI-видеогенерации', 'экономии кредитов', 'кредитами экономит', 'стоимость кредитов генераций'],
        'search_args': [],
        'expected_keys': ['cgevent:16497', 'cgevent:16312'],
        'min_hits': 2,
        'note': 'морфо-тест FTS: ключи из покрытия (тема 5)',
        'provenance': '20260920-100332-460653',
    },
    {
        'id': 'negative_control_out_of_corpus',
        'kind': 'negative_control',
        'tags': ['negative_control'],
        'question': 'Какие в корпусе экспертов есть протоколы секвенирования ДНК и биоинформатические пайплайны для NGS-данных?',
        'query_variants': [],
        'search_args': [],
        'expected_keys': [],
        'min_hits': 0,
        'allow_context_citations': True,
        'note': 'Ссылки на прочитанный смежный контекст допустимы; его уместность и оговорки оцениваются по рубрике.',
        'provenance': 'manual_negative_control',
        'reviewed_at': '2026-09-30',
        'rubric': 'Явно сказать, что конкретные протоколы NGS не найдены в проверенных материалах. Смежный контекст допустим только с объяснением, чего он не подтверждает; не выдавать его за ответ, не придумывать инструкции и не объявлять доказанным отсутствие во всём корпусе.',
        'evidence': {},
    },

    {'id': 'videohub_liquid_speed_ramp',
     'kind': 'hit',
     'tags': ['scope_videohub', 'historical_repair'],
     'question': 'По ВидеоХабу: как подготовить в Blender рекламный ролик с жидкостью и резкими ускорениями '
                 'камеры? Нужны конкретные приёмы: что оставляют вместо симуляции жидкости и как задают speed '
                 'ramp до AI-генерации.',
     'query_variants': [],
     'search_args': ['--experts', 'video_hub'],
     'expected_keys': ['video_hub:276863315', 'video_hub:210678333'],
     'min_hits': 2,
     'note': 'Регрессия найденной и исправленной исторической потери; проверено полным show.',
     'provenance': 'source_review:2026-09-30',
     'reviewed_at': '2026-09-30',
     'rubric': 'Чёрная заглушка вместо блокинга жидкости; speed ramp задаётся изменением блокинга, а не общим '
               'советом экономить кредиты.',
     'evidence': {'video_hub:276863315': 'Keep it black in the block out, and let the AI fill it in later.',
                  'video_hub:210678333': 'The camera slams in, pauses for a beat, and accelerates into the next '
                                         'cut.'}},

    {'id': 'videohub_dialogue_language',
     'kind': 'hit',
     'tags': ['scope_videohub', 'historical_repair'],
     'question': 'По ВидеоХабу: как Youri предлагает задавать язык и акцент реплик, где хранить текст реплик и '
                 'где указывать момент их произнесения? Нужны конкретные инструкции эксперта.',
     'query_variants': [],
     'search_args': ['--experts', 'video_hub'],
     'expected_keys': ['video_hub:231192822'],
     'min_hits': 1,
     'note': 'Регрессия найденной и исправленной исторической потери; проверено полным show.',
     'provenance': 'source_review:2026-09-30',
     'reviewed_at': '2026-09-30',
     'rubric': 'Язык/акцент и подача в dialogue block; реплики повторены по порядку; шот задаёт когда, dialogue '
               'задаёт что и как.',
     'evidence': {'video_hub:231192822': 'This is also where you name the language and the accent, if you want '
                                         'to.'}},

    {'id': 'videohub_character_sheet_model',
     'kind': 'hit',
     'tags': ['scope_videohub', 'historical_repair'],
     'question': 'По ВидеоХабу: какую модель Dan Kieft использует для character sheet в уроке про реалистичные '
                 'видео Seedance 2.5, почему убирает шляпу и как закрепляет внешность героя?',
     'query_variants': [],
     'search_args': ['--experts', 'video_hub'],
     'expected_keys': ['video_hub:763320226'],
     'min_hits': 1,
     'note': 'Регрессия найденной и исправленной исторической потери; проверено полным show.',
     'provenance': 'source_review:2026-09-30',
     'reviewed_at': '2026-09-30',
     'rubric': 'Seedream 5.0 Pro, не SeaArt; убрать мелкую деталь; sheet и портрет как identity references, '
               'запреты recast/beautify.',
     'evidence': {'video_hub:763320226': "I'm now using Seedream 5.0 Pro when I generate these character "
                                         'sheets.'}},

    {'id': 'videohub_fake_fall',
     'kind': 'hit',
     'tags': ['scope_videohub', 'historical_repair'],
     'question': 'По ВидеоХабу: по каким признакам в разборе VFX можно заметить ненастоящее падение цифрового '
                 'дублёра с обрыва? Какие именно ошибки движения и внешности отмечает автор?',
     'query_variants': [],
     'search_args': ['--experts', 'video_hub'],
     'expected_keys': ['video_hub:445026460'],
     'min_hits': 1,
     'note': 'Регрессия найденной и исправленной исторической потери; проверено полным show.',
     'provenance': 'source_review:2026-09-30',
     'reviewed_at': '2026-09-30',
     'rubric': 'Постоянная скорость без ускорения, жёсткая поза, нет движения одежды/конечностей; меняются '
               'кроссовки.',
     'evidence': {'video_hub:445026460': 'No acceleration, nothing moving in the clothes or the limbs.'}},
]

# Paired questions share source evidence with the original cases. Only the
# wording and semantic task differ; the agent never receives the gold/rubric.
_by_id = {fixture['id']: fixture for fixture in FIXTURES}
FIXTURES.extend([
    {
        **_by_id['videohub_liquid_speed_ramp'],
        'id': 'videohub_liquid_plain_language',
        'tags': ['scope_videohub', 'plain_language'],
        'question': 'По ВидеоХабу: как подготовить рекламный ролик, чтобы камера резко разгонялась и притормаживала? А кусок с льющейся жидкостью обязательно заранее делать в Blender?',
        'note': 'Парный вопрос без терминов speed ramp и блокинг; те же два приёма и источника.',
    },
    {
        **_by_id['videohub_character_sheet_model'],
        'id': 'videohub_character_sheet_false_premise',
        'tags': ['scope_videohub', 'false_premise'],
        'question': 'По ВидеоХабу: в разборе Dan Kieft про реалистичные видео Seedance 2.5 таблицу персонажа делают в SeaArt, правильно? Как он это делает?',
        'note': 'Ошибочная подсказка пользователя; наличие правильной ссылки само по себе не доказывает исправления ошибки.',
        'rubric': 'Явно исправить SeaArt на Seedream 5.0 Pro со ссылкой на источник. Объяснить подготовку character sheet по материалу Dan; не приписывать этот процесс SeaArt и не сочинять его настройки. Проверять смысл вручную: слова SeaArt и Seedream сами по себе ничего не доказывают.',
    },
])
del _by_id
