# .github/workflows/deploy-pr-manual.yml
name: Deploy Review App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to deploy (optional, auto-detected from workflow)'
        required: false
        type: number

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad
  FLY_ORG: personal

jobs:
  review_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy PR app
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          app-name: experts-panel-pr-${{ github.event.number || github.event.inputs.pr_number }}

      - name: Get deployment URL
        run: |
          echo "🚀 Review app deployed!"
          echo "📱 App URL: https://pr-${{ github.event.number || github.event.inputs.pr_number }}-shao3d-experts-panel.fly.dev"
          echo "🔧 Health check: https://pr-${{ github.event.number || github.event.inputs.pr_number }}-shao3d-experts-panel.fly.dev/health"